spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.31.205:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  thymeleaf:
    check-template-location: true
  redis:
    host: 192.168.31.205
    port: 6379
server:
  servlet:
    context-path: /sell


projectUrl:
  sell: http://wuhao191919.nat300.top



